"""rich text posts

Revision ID: 219c394864cf
Revises: e1bf7fa7bc8e
Create Date: 2019-08-14 10:21:20.526842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '219c394864cf'
down_revision = 'e1bf7fa7bc8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
